### ISSUE TITLE
Issues with linked MoveNet example

### ISSUE THREAD

**Issue by gohai** [ml5js/ml5-website-v02-docsify#171]
Hi 👋,

The reference for BodyPose includes a link to [this example sketch](https://editor.p5js.org/ml5/sketches/vpSI23x0A) for MoveNet.

This seems to be still be referencing the `ml5@0.20.0-alpha.4` version of the library. (It also makes use of `score` rather than `confidence` - which is what the website refers to.)

**Comment by alanvww** [comment]
Thanks a lot, @gohai, for bringing this issue to our attention! 

@MOQN @ziyuan-linn I double-checked the p5 collection, and the movenet skeleton is still using `ml5@0.20.0-alpha.4`, as mentioned earlier. However, there’s a sketch called [`bodyPose-skeleton`](https://editor.p5js.org/ml5/sketches/hMN9GdrO3) that uses the correct version. Should we replace the example using this one instead?

**Comment by ziyuan-linn** [comment]
Thank you @gohai and @alanvww. Yes we should switch to `bodyPose-skeleton`. We decided to remove "movenet" from the sketch name a while ago since `movenet` is the default model of `bodyPose`. I think I forgot to delete the other sketch.

For reference, only sketches in the `examples` folder of `ml5-next-gen` are maintained and automatically updated.

**Comment by alanvww** [comment]
> Thank you @gohai and @alanvww. Yes we should switch to `bodyPose-skeleton`. We decided to remove "movenet" from the sketch name a while ago since `movenet` is the default model of `bodyPose`. I think I forgot to delete the other sketch.
> 
> For reference, only sketches in the `examples` folder of `ml5-next-gen` are maintained and automatically updated.

Got it! I will update the docs later.

**Comment by gohai** [comment]
Many thanks @alanvww 🎉🙌
