### ISSUE TITLE
image classifier Teachable Machine Support

### ISSUE THREAD

**Issue by QuinnHe** [ml5js/ml5-website-v02-docsify#60]
Hi @ziyuan-linn , we are working on the documentation page for Image + Teachable Machine. I tried to have it running with our alpha release but got an error, please check this [sketch](https://editor.p5js.org/fh805/sketches/XrHisggQka) for more info. 

@MOQN , @shiffman Hi Dan, Moon, for now, I used image classifier methods of the old version on our [documentation page](https://ml5-next-gen-docs.netlify.app/#/reference/image-classifier-tm), once we have the support for the alpha release, we can update the documentation page accordingly.

And so far we have covered all the alpha release models documented by the new website.

**Comment by ziyuan-linn** [comment]
Hi @QuinnHe, thank you for letting me know about this! Looks like this problem only occurs with the webgpu backend.

For now, we can force tfjs to use the WebGL backend instead:
```js
function preload() {
  ml5.setBackend("webgl"); //<--- add this
  classifier = ml5.imageClassifier(imageModelURL + "model.json");
}
```
After adding this line, the error disappeared for me.

---
Tagging @OrpheasK here. Looks like the problem is happening in this block in `src/ImageClassifier/index.js`:
```js
      const predictedClasses = tf.tidy(() => {
        const predictions = this.model.predict(imgToPredict);
        return Array.from(predictions.as1D().dataSync());
      });
```
I think the `dataSync` function needs to be changed to `data`. We can also try to work on this during today's meeting.

**Comment by QuinnHe** [comment]
Used Peter's @ziyuan-linn  temp solution for now, can update accordingly if we update the source code.
